// AUTO-GENERATED by scripts/gen-index.sh — do not edit by hand.
#import "../vendor/bookly/src/bookly.typ": part

#part([The Architecture])

#include "intro-00-replaceable-compute.typ"
#include "intro-01-cells-and-placement.typ"
#include "intro-02-one-cell-one-write-boundary.typ"
#include "intro-03-epochs-artifacts-overlays.typ"
#include "intro-04-from-cypher-to-roaring.typ"
#include "intro-05-bounded-distributed-queries.typ"

#part([Implementation Deep Dives])

#include "detail-01-roaring-matrix-rows.typ"
#include "detail-02-write-edge-path.typ"
