#!/usr/bin/env bash
#
# Regenerate book/chapters/_index.typ from the .typ files in book/chapters/.
#
# This is what makes the book index "automatically updated": Typst itself
# cannot list a directory, so this script scans chapters/, groups files into
# #part(...) sections by filename prefix, and emits the #include list that
# main.typ pulls in. Drop a new chapter file into chapters/ (named with a
# known prefix), re-run this script (or `make -C book index`), and it appears
# in the book — no hand-edit of main.typ. Everything downstream (table of
# contents, figure/table numbering, cross-references) is regenerated by Typst
# on the next compile.
#
# Naming convention -> part:
#   intro-*    -> "Part I · The Intuition Track"        (the persona read)
#   detail-*   -> "Part II · The Implementation Track"  (the coder read)
#   anything else -> "Other"
# Concept N pairs across tracks: intro-NN-slug <-> detail-NN-slug.
# Within a part, files are ordered lexically by filename (so NN drives order).
set -euo pipefail

cd "$(dirname "$0")/.."   # -> book/
CH="chapters"
OUT="$CH/_index.typ"

{
  echo "// AUTO-GENERATED by scripts/gen-index.sh — do not edit by hand."
  echo "// Regenerate after adding/removing a chapter: make -C book index"
  # #include does not inherit the parent file's imports, so this generated
  # file must import #part itself. Paths here are relative to chapters/.
  echo "#import \"../vendor/bookly/src/bookly.typ\": part"
} >"$OUT"

emit_part() {
  local title="$1" prefix="$2" opened=0 f
  for f in "$CH"/${prefix}*.typ; do
    [ -e "$f" ] || continue
    if [ "$opened" -eq 0 ]; then
      printf '\n#part([%s])\n\n' "$title" >>"$OUT"
      opened=1
    fi
    printf '#include "%s"\n' "$(basename "$f")" >>"$OUT"
  done
}

emit_part "The Intuition Track" "intro-"
emit_part "The Implementation Track" "detail-"

# Catch-all: any chapter whose name matches no known prefix.
opened=0
for f in "$CH"/*.typ; do
  base="$(basename "$f")"
  case "$base" in
  _index.typ | intro-* | detail-*) continue ;;
  esac
  if [ "$opened" -eq 0 ]; then
    printf '\n#part([Other])\n\n' >>"$OUT"
    opened=1
  fi
  printf '#include "%s"\n' "$base" >>"$OUT"
done

echo "wrote $OUT"
