apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slatedb-graph
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - configmap.yaml
  - node-statefulset.yaml
  - controller-statefulset.yaml
  - services.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
labels:
  - pairs:
      app.kubernetes.io/name: slatedb-graph
      app.kubernetes.io/part-of: slatedb-graph
    includeSelectors: true
images:
  - name: ghcr.io/usecortex/slatedb-graph-kernel
    newTag: 0.1.0
