apiVersion: v1
kind: Namespace
metadata:
  name: slatedb-graph
  labels:
    app.kubernetes.io/name: slatedb-graph
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
