apiVersion: v1
kind: ServiceAccount
metadata:
  name: graph-node
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graph-controller
automountServiceAccountToken: false
