// AUTO-GENERATED by scripts/gen-index.sh — do not edit by hand.
// Regenerate after adding/removing a chapter: make -C book index
#import "../vendor/bookly/src/bookly.typ": part

#part([The Intuition Track])

#include "intro-00-orientation.typ"
#include "intro-01-uid-sets.typ"
#include "intro-02-roaring-dense-uids.typ"
#include "intro-03-graph-model.typ"
#include "intro-04-s3-substrate.typ"
#include "intro-05-write-path.typ"
#include "intro-06-single-writer.typ"
#include "intro-07-indexes.typ"
#include "intro-08-read-path.typ"
#include "intro-09-reader-writer.typ"

#part([The Implementation Track])

#include "detail-01-posting-values.typ"
#include "detail-02-uids-identity.typ"
#include "detail-03-node-schema-records.typ"
#include "detail-04-substrate-keyspace.typ"
