#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
chapters="$root/chapters"
output="$chapters/_index.typ"
tmp="$output.tmp"
emitted=0

emit_part() {
  local title="$1"
  local pattern="$2"
  local matches=()
  while IFS= read -r file; do matches+=("$file"); done < <(
    find "$chapters" -maxdepth 1 -type f -name "$pattern" -print | sort
  )
  if [ "${#matches[@]}" -eq 0 ]; then return; fi
  if [ "$emitted" -eq 1 ]; then printf '\n' >> "$tmp"; fi
  printf '#part([%s])\n\n' "$title" >> "$tmp"
  for file in "${matches[@]}"; do
    printf '#include "%s"\n' "$(basename "$file")" >> "$tmp"
  done
  emitted=1
}

printf '// AUTO-GENERATED by scripts/gen-index.sh — do not edit by hand.\n' > "$tmp"
printf '#import "../vendor/bookly/src/bookly.typ": part\n\n' >> "$tmp"
emit_part "The Architecture" 'intro-*.typ'
emit_part "Implementation Deep Dives" 'detail-*.typ'
emit_part "Cache Keys and Values" 'turbolay-*.typ'
mv "$tmp" "$output"
