#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESULTS="${GRAPH_QUERY_BENCH_RESULTS:-$ROOT/bench-results/query_bench_full.csv}"
LOG="${GRAPH_QUERY_BENCH_LOG:-$ROOT/bench-results/query_bench_full.log}"
FANOUTS="${GRAPH_QUERY_BENCH_FANOUTS:-50,100,1000,5000,10000}"
HOPS="${GRAPH_QUERY_BENCH_HOPS:-1,5,10,15,20}"
DATA_HOPS="${GRAPH_QUERY_BENCH_DATA_HOPS:-20}"
COLD_ITERS="${GRAPH_QUERY_BENCH_COLD_ITERS:-5}"
HOT_ITERS="${GRAPH_QUERY_BENCH_HOT_ITERS:-9}"
INDEX_POLICY="${GRAPH_QUERY_BENCH_INDEX_POLICY:-outbound-only}"
BULK_CHUNK_SIZE="${GRAPH_QUERY_BENCH_BULK_CHUNK_SIZE:-10000}"
WORKLOADS="${GRAPH_QUERY_BENCH_WORKLOADS:-all}"
MODE="${GRAPH_QUERY_BENCH_MODE:-full}"
MAX_GRAPHBLAS_MATRICES="${GRAPH_QUERY_BENCH_MAX_GRAPHBLAS_MATRICES:-1}"
MAX_MATRIX_ADJACENCIES="${GRAPH_QUERY_BENCH_MAX_MATRIX_ADJACENCIES:-0}"
MAX_REACHABILITY_RESULTS="${GRAPH_QUERY_BENCH_MAX_REACHABILITY_RESULTS:-0}"
RUNTIME="${GRAPH_QUERY_BENCH_RUNTIME:-multi-thread}"
RUNTIME_WORKERS="${GRAPH_QUERY_BENCH_RUNTIME_WORKERS:-}"
CONCURRENCY="${GRAPH_QUERY_BENCH_CONCURRENCY:-8}"
CONCURRENT_ITERS="${GRAPH_QUERY_BENCH_CONCURRENT_ITERS:-16}"
PAGE_SIZE="${GRAPH_QUERY_BENCH_PAGE_SIZE:-64}"
FEATURES="${GRAPH_QUERY_BENCH_FEATURES:-opencypher}"

export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/dgraph-query-target}"
mkdir -p "$(dirname "$RESULTS")" "$(dirname "$LOG")"

if [[ "${GRAPH_QUERY_BENCH_APPEND:-0}" != "1" ]]; then
  rm -f "$RESULTS" "$LOG"
fi

cd "$ROOT"
IFS=',' read -ra fanout_list <<< "$FANOUTS"
for fanout in "${fanout_list[@]}"; do
  tmp="$(mktemp)"
  echo "query bench mode=$MODE workloads=$WORKLOADS fanout=$fanout hops=$HOPS data_hops=$DATA_HOPS cold_iters=$COLD_ITERS hot_iters=$HOT_ITERS index_policy=$INDEX_POLICY bulk_chunk_size=$BULK_CHUNK_SIZE graphblas_matrices=$MAX_GRAPHBLAS_MATRICES matrix_adjacencies=$MAX_MATRIX_ADJACENCIES reachability_results=$MAX_REACHABILITY_RESULTS concurrency=$CONCURRENCY concurrent_iters=$CONCURRENT_ITERS page_size=$PAGE_SIZE features=$FEATURES" | tee -a "$LOG" >&2
  GRAPH_QUERY_BENCH_FANOUTS="$fanout" \
    GRAPH_QUERY_BENCH_HOPS="$HOPS" \
    GRAPH_QUERY_BENCH_DATA_HOPS="$DATA_HOPS" \
    GRAPH_QUERY_BENCH_COLD_ITERS="$COLD_ITERS" \
    GRAPH_QUERY_BENCH_HOT_ITERS="$HOT_ITERS" \
    GRAPH_QUERY_BENCH_INDEX_POLICY="$INDEX_POLICY" \
    GRAPH_QUERY_BENCH_BULK_CHUNK_SIZE="$BULK_CHUNK_SIZE" \
    GRAPH_QUERY_BENCH_WORKLOADS="$WORKLOADS" \
    GRAPH_QUERY_BENCH_MODE="$MODE" \
    GRAPH_QUERY_BENCH_MAX_GRAPHBLAS_MATRICES="$MAX_GRAPHBLAS_MATRICES" \
    GRAPH_QUERY_BENCH_MAX_MATRIX_ADJACENCIES="$MAX_MATRIX_ADJACENCIES" \
    GRAPH_QUERY_BENCH_MAX_REACHABILITY_RESULTS="$MAX_REACHABILITY_RESULTS" \
    GRAPH_QUERY_BENCH_RUNTIME="$RUNTIME" \
    GRAPH_QUERY_BENCH_RUNTIME_WORKERS="$RUNTIME_WORKERS" \
    GRAPH_QUERY_BENCH_CONCURRENCY="$CONCURRENCY" \
    GRAPH_QUERY_BENCH_CONCURRENT_ITERS="$CONCURRENT_ITERS" \
    GRAPH_QUERY_BENCH_PAGE_SIZE="$PAGE_SIZE" \
    cargo run --release --features "$FEATURES" --example query_bench > "$tmp" 2>> "$LOG"
  if [[ ! -s "$RESULTS" ]]; then
    cat "$tmp" >> "$RESULTS"
  else
    tail -n +2 "$tmp" >> "$RESULTS"
  fi
  rm -f "$tmp"
done
