apiVersion: v1
kind: Service
metadata:
  name: graph-bolt
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    external-dns.alpha.kubernetes.io/hostname: graph-bolt.REPLACE_PRIVATE_DNS_ZONE
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: graph-https
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
