apiVersion: v1
kind: ServiceAccount
metadata:
  name: graph-node
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/REPLACE_GRAPH_DATA_S3_ROLE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graph-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/REPLACE_GRAPH_CONTROL_S3_ROLE
